# Generated by Django 4.2 on 2023-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='size',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
